# -*- coding: utf-8 -*-
"""Assignment2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/161nEmQYul5gTFdzzyG5KP2XmCl5Z60I7
"""

#Number Guessing game
import random

random_number=random.randint(1,50)
while True:
  try:
    num=int(input("Enter a number between 1-50: "))
    if(num<random_number):
      print("Number is too low, Try again")

    elif(num>random_number):
      print("Number is too high, Try again")
    else:
      print("Correct")
      break;
  except:
    print("Invaid input!")

#Student Grade Cacuator

def calcuate_grade(marks):

  if(marks>=90):
    return "A"
  elif(marks>=80):
    return "B"
  elif(marks>=70):
    return "C"
  elif(marks>=60):
    return "D"
  else:
    return('Failed')
marks=int(input(f"Enter your marks: "))
print(f"Your marks is: {calcuate_grade(marks)}")

#Cinema price
age=int(input("Enter your age: "))
day=int(input("Enter the day of the week: "))
price=0
if(age<=12):
  price=300
elif(age>=12 and age<17):
  price=500
elif(age>=18 and age<59):
  price=800
elif(age>60):
  price=400
else:
  print("Invalid age")

if(day==3):
  print("Happy wedensday! You get 100 off")
  price-=100



print(f"Your price is: {price}")